package main

func main() {
	arrayRotate()
	bestSightSeeingPair()
	chefCooking()
	combineNumber()
	duplicateNumber()
	equal_circle_segments()
	findClosestValueMain()
	flattenend()
	gameLife()
	// getMinConnectionCostMain()
	getTheGroupsMain()
	groupAnagramsMain()
	hIndexMain()
	// increasingTripletSubsequence()
	isHappyMain()
	insertDeleteRandom()
	insertInterval()
	lineThroughPointsMain()
	longestConsecutiveSequence()
	longestSubArraySumKMain()
	maxSubarrayKadane()
	minChairs()
	mmtInterviewCovid()
	move0StartMain()
	moveNegativeToEnd()
	nonOverlapingIntervals()
	onCallDays()
	pairWithGivenSum()
	pascalTriangle()
	// powersetMain()
	productArrayExceptSelfMain()
	reachTheEnd()
	rearrangeMaxMin()
	removeDuplicatesMain()
	rotate1DArrayByKMain()
	rotateImage()
	setZeroesMain()
	sliceUnderstanding()
	// snapshotArray()
	sortOddEven()
	sort012Main()
	sortedMatrixSearch()
	spiralMatrix()
	stockMaxProfit()
	subarraySumEqualsK()
	sunset()
	taskManagementMain()
	validSudoku()
	watchMovies()
	maxSumMain()
	zigzag()
}
