package main

func main() {
	airportConnectionsMain()
	bfsMain()
	boggleBoard()
	cloneGraphMain()
	courseSchedule()
	courseSchedule2()
	cycleGraph()
	detectArbitrageMain()
	dfsMain()
	evaluateDivision()
	minGeneMutationMain()
	minPassMatrixMain()
	minRectangle()
	numOfIslandsMain()
	removeIslandsMain()
	riverSizeMain()
	shortestPath()
	smallCycleCheck()
	snakesLadderMain()
	surroundedRegions()
	twoEdgeConnected()
	youngestCommonAncestor()
}
