package main

func main() {
	allKindOfNodeDepth()
	balancedBT()
	binaryTree()
	branchSumMain()
	bstIteratorMain()
	bstIterator2Main()
	compareLeafMain()
	countCompleteTreenNodes()
	createTreeFromInorderPostorderTraversal()
	createTreeFromPreorderInorderTraversal()
	findNodeDistanceKMain()
	findSuccessorMain()
	flattendBT2Approach()
	// flattendBTMain() => as they are not right
	flattendBTPreorderMain()
	// flattendBTPostorderMain() => as they are not right
	invertTree()
	IterativeInOrderTraversalWithParent()
	levelOrderIteration()
	lowestCommonAncestorMain()
	maxDepthMain()
	maxPathSumMain()
	morrisTraversal()
	nodeDepthsIterMain()
	nodeDepthsMain()
	pathSum()
	rightSiblingInNextPointer()
	rightSiblingTreeMain()
	isSameTreeMain()
	sumRootToLeaf()
	symmetricTree()
}
