package main

func main() {
	climbingStairsMain()
	diskStackingMain()
	houseRobber()
	knapsackMain()
	levenshtienDistance()
	longestCommonSubsequenceMain()
	longestIncreasingSubsequence()
	longestPalindromString()
	maxEnergyMain()
	maxSeparation()
	maxSubsetSumNoAdjacentMain()
	maxSumIncreasingSubsequence()
	maximizeExpressionMain()
	maximumSumSubmatrix()
	minNoJumps()
	minNoOfWaysToMakeChange()
	mmtInterviewJobScheduling()
	mostPowerfulAlliance()
	noOfWaysToMakeChange()
	noOfWaysTraverseGraph()
	numbersInPi()
	waterArea()
}
